Formatting fixes
Setotet/secgov pull request #7
Opened 2024-05-14 16:38 UTC by MrSaighnal

Fixed all formatting issues related to in-line references and added a new contributor.

2024-05-15 15:01 UTC, mattbit approved these changes

2024-05-15 15:01 UTC, mattbit commented on 1_1_vulns/it-IT/LLM05_SupplyChainVulnerabilities.md
> +11. [LLM07 - Insecure Plugin Design](InsecurePluginDesign.md)
Not sure this would work

2024-05-17 04:29 UTC, Setotet requested changes
No links to personal repository; it can be deleted anytime.

2024-05-17 04:29 UTC, Setotet commented on 1_1_vulns/it-IT/LLM05_SupplyChainVulnerabilities.md
> +11. [LLM07 - Insecure Plugin Design](https://github.com/Setotet/secgov/blob/main/1_1_vulns/en-ZZ/InsecurePluginDesign.md)
Pls do not link to personal repository.  It can be deleted anytime.

2024-05-19 08:26 UTC, Setotet reviewed
Why referring back to the English version?

2024-05-19 08:26 UTC, Setotet commented on 1_1_vulns/it-IT/LLM05_SupplyChainVulnerabilities.md
> +Infine, le estensioni dei plugin LLM possono introdurre ulteriori vulnerabilità. Queste sono descritte in LLM07 - Progettazione Insicura dei Plugin (OWASP Top 10 for LLM Applications v. 1.1, 2023, p.
Why referring to LLM07 section of the English v.1.1 from Italian v1.1?

2024-05-20 13:22 UTC, MrSaighnal commented on 1_1_vulns/it-IT/LLM05_SupplyChainVulnerabilities.md
> +11. [LLM07 - Insecure Plugin Design](https://github.com/Setotet/secgov/blob/main/1_1_vulns/en-ZZ/InsecurePluginDesign.md)
I think is fixed now

2024-05-21 10:44 UTC, mattbit commented
I note down the bugs found after a quick review

## Bugs

- [ ]  author names are shown in the table of contents (Steve Wilson, Ads Dawson)
- [ ] inconsistency between normal and title case e.g. "Gestione non sicura dall-output", "Diffusione di Informazioni Sensibilii"
- [ ] inconsistency in vulnerability subsections:
    - "Strategie di prevenzione e mitigazione/Strategie di Mitigazione e Prevenzione"
    - "Esempi di Scenari di Attacco/Esempi di scenario d'attacco"
    - "Riferimenti e link/Referenze e link/Link e riferimenti"
- [ ] Page 7, there's a head orphan "Esempi comuni di vulnerabilità"
- [ ] Page 21,  there's an unwanted line break in the "Descrizione" "OWASP Top 10 per //// le applicazioni LLM"
- [ ] Page 26, missing reference for "Supply-Chain-Vulnerabilities"?
- [ ] LLM08: heading for "Descrizione" is missing margin?
- [ ] Page 31: "Esempi di Scenari di Attacco" has several `<br>` tags in the paragraph
- [ ] Page 31 orphan heading "Riferimenti e link"
- [ ] Page 38: wrong italic `applicazione LLM "_ha accesso_"`

2024-05-21 11:55 UTC, MrSaighnal commented
> I note down the bugs found after a quick review
> 
> ## Bugs
> * [x]   author names are shown in the table of contents (Steve Wilson, Ads Dawson)
> * [ ]  inconsistency between normal and title case e.g. "Gestione non sicura dall-output", "Diffusione di Informazioni Sensibilii"
> * [x]  inconsistency in vulnerability subsections:
>   
>   * "Strategie di prevenzione e mitigazione/Strategie di Mitigazione e Prevenzione"
>   * "Esempi di Scenari di Attacco/Esempi di scenario d'attacco"
>   * "Riferimenti e link/Referenze e link/Link e riferimenti"
> * [x]  Page 7, there's a head orphan "Esempi comuni di vulnerabilità"
> * [x]  Page 21,  there's an unwanted line break in the "Descrizione" "OWASP Top 10 per //// le applicazioni LLM"
> * [x]  Page 26, missing reference for "Supply-Chain-Vulnerabilities"?
> * [x]  LLM08: heading for "Descrizione" is missing margin?
> * [x]  Page 31: "Esempi di Scenari di Attacco" has several `<br>` tags in the paragraph
> * [x]  Page 31 orphan heading "Riferimenti e link"
> * [x]  Page 38: wrong italic `applicazione LLM "_ha accesso_"`

2024-05-22 11:48 UTC, Setotet approved these changes

2024-05-24 14:27 UTC, merged